# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier (relative path below content folder) of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Funções"
pageRef = "pages/functions"
weight = 10

[[main]]
name = "Produtos"
pageRef = "#0"
weight = 20

[[main]]
name = "Visão geral"
parent = "Produtos"
pageRef = "pages/product/overview"
weight = 21

[[main]]
name = "Nuvem SeaTable"
parent = "Produtos"
pageRef = "pages/product/seatable-cloud"
weight = 22

[[main]]
name = "SeaTable Dedicado"
parent = "Produtos"
pageRef = "pages/product/seatable-dedicated"
weight = 23

[[main]]
name = "Servidor SeaTable"
parent = "Produtos"
pageRef = "pages/product/seatable-server"
weight = 24

[[main]]
name = "Soluções"
pageRef = "#0"
weight = 30

[[main]]
name = "Marketing"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/marketing"
weight = 31

[[main]]
name = "Gestão de Projectos"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/project-management"
weight = 32

[[main]]
name = "Recursos Humanos"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/hr"
weight = 33

[[main]]
name = "Setor Público"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/public-service"
weight = 34

[[main]]
name = "Desenvolvimento de Software"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/software-development"
weight = 35

[[main]]
name = "Personalizado"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/individual"
weight = 36

[[main]]
name = "Operações"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/operations"
weight = 37

[[main]]
name = "Vendas"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/kundenmanagement"
weight = 39

[[main]]
name = "Finanças"
parent = "Soluções"
pageRef = "pages/landing-pages/industry-solutions/finanzplan-erstellen"
weight = 38

[[main]]
name = "Recursos"
pageRef = "#0"
weight = 40

[[main]]
name = "Modelos"
parent = "Recursos"
pageRef = "templates"
weight = 42

[[main]]
name = "Guia rápido"
parent = "Recursos"
pageRef = "pages/quick-guide"
weight = 43

[[main]]
name = "Curso on-line"
parent = "Recursos"
pageRef = "help/erste-schritte"
weight = 44

[[main]]
name = "Ajuda"
parent = "Recursos"
pageRef = "help"
weight = 45

#[[main]]
#name = "Integrations"
#parent = "Recursos"
#pageRef = "posts"
#weight = 46

[[main]]
name = "Fórum"
parent = "Recursos"
url = "https://forum.seatable.com"
weight = 47

[[main]]
name = "Blogue"
parent = "Recursos"
pageRef = "posts"
weight = 48

[[main]]
name = "Casos de sucesso"
parent = "Recursos"
pageRef = "categories/customer-story"
weight = 49

[[main]]
name = "Prices"
pageRef = "pages/prices"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Produtos"
weight = 10

[[footer]]
name = "Nuvem SeaTable"
parent = "Produtos"
pageRef = "pages/product/seatable-cloud"
weight = 11

[[footer]]
name = "SeaTable Dedicado"
parent = "Produtos"
pageRef = "pages/product/seatable-dedicated"
weight = 12

[[footer]]
name = "Servidor SeaTable"
parent = "Produtos"
pageRef = "pages/product/seatable-server"
weight = 13

[[footer]]
name = "Apoio"
parent = "Produtos"
pageRef = "pages/support"
weight = 14

[[footer]]
name = "Apoio a"
weight = 20

[[footer]]
name = "Guia rápido"
parent = "Apoio a"
pageRef = "pages/quick-guide"
weight = 21

[[footer]]
name = "Área de ajuda"
parent = "Apoio a"
pageRef = "help"
weight = 22

[[footer]]
name = "Modelos"
parent = "Apoio a"
pageRef = "templates"
weight = 23

[[footer]]
name = "Integrações"
parent = "Apoio a"
pageRef = "pages/integrations"
weight = 24

[[footer]]
name = "Fórum"
parent = "Apoio a"
url = "https://forum.seatable.com"
weight = 25

[[footer]]
name = "API para programadores"
parent = "Apoio a"
url = "https://api.seatable.com"
weight = 26

[[footer]]
name = "Estado"
parent = "Apoio a"
url = "https://status.seatable.com"
weight = 27

[[footer]]
name = "A empresa"
weight = 30

[[footer]]
name = "Sobre nós"
parent = "A empresa"
pageRef = "pages/about"
weight = 31

[[footer]]
name = "Empregos"
parent = "A empresa"
pageRef = "pages/jobs"
weight = 32

[[footer]]
name = "Imprensa"
parent = "A empresa"
pageRef = "pages/press"
weight = 33

[[footer]]
name = "Contactar-nos"
parent = "A empresa"
pageRef = "pages/contact"
weight = 34

[[footer]]
name = "Blogue"
parent = "A empresa"
pageRef = "posts"
weight = 35

# -- Legal Disclaimer --
# The last line of the page with links to the legal pages.

[[legal]]
name = "Impressão"
pageRef = "pages/legal/imprint"
weight = 10

[[legal]]
name = "Legal"
pageRef = "pages/legal/overview"
weight = 20

[[legal]]
name = "Segurança"
pageRef = "pages/legal/security"
weight = 30
